### ISSUE TITLE
aiohttp ClientSession as attribute of cogs, or attribute of bot?

### ISSUE THREAD

**Issue by Vexs** [DBDU/union#16]
Question in title. Do we want a separate clientsession defined per-cog, or do we want it as an attribute of the bot itself?

**Comment by Fuyukai** [comment]
there's no advantage to doing either except slightly less memory usage on one session

**Comment by Vexs** [comment]
Yeah, but it's still a thing best decided early on as it will affect the construction of cogs slightly. I say go for bot.session

**Comment by Vexs** [comment]
Decided via discord, clientsession is now an attribute of bot as part of #26
