### ISSUE TITLE
Administration/core cog

### ISSUE THREAD

**Issue by indiv0** [DBDU/union#5]
Should include:

* ~~moderation tools~~ (will be in a separate cog, handled under #6)
* [x] debug/eval
* [x] change
    * [x] name
    * [x] avatar
    * [x] game
    * [x] status
* [ ] load/unload
* [x] shutdown
* [ ] uptime
* [ ] (maybe) info
* [ ] (maybe) restart

**Comment by Vexs** [comment]
Why put name/avatar into it when it's simple enough to do with an eval? Shouldn't be a common thing anyhow. Also, kinda weirdish, but perhaps an upload/download file command that uploads files that are uploaded to discord as attachments? Comes in handy for quick updates, or if a file got missed somewhere, etc.

As a thought, could put the avatar SVGs/pngs on the github, could have the bot autofetch like that.

**Comment by indiv0** [comment]
Should we create a general utility cog? It *would* be very simple to do name/avatar changes with an eval but I think we should add functionality (at some point down the line) for most things as long as they're not *absolutely* trivial, because we can't expect the majority of our userbase to be able to use eval.

👍 to both your other ideas/suggestions. Feel free to make issues for them.

**Comment by Vexs** [comment]
Ah, good point on that, forgot this isn't all us-sided.
