### ISSUE TITLE
User-sided moderation tools

### ISSUE THREAD

**Issue by Vexs** [DBDU/union#6]
As part of: #4
Basic parts:

- [ ] Bans/hackbans (why bother with two commands? Why not one?)
- [ ] Softban
- [ ] Unban
- [ ] Logging
- - [ ] Deleted Messages
- - [ ] Edited messages
- - [ ] Avatar changes (Maybe?)
- - [ ] Joins/Leaves
- [ ] Mute
- [ ] Case system (Pollr-like)
- [ ] Audit log support
- - [ ] Audit log logging (Search audit logs past 90 days, etc)
- [ ] AntiSpam functionality (Perhaps more suited for it's own cog)

**Comment by indiv0** [comment]
Part of this will be added in by Beta as mod tools were originally (erroneously) mentioned in issue #5.

**Comment by Vexs** [comment]
Closed, moved to https://github.com/DBDU/cogs/issues/4
