### ISSUE TITLE
Choose a license for the project

### ISSUE THREAD

**Issue by indiv0** [DBDU/union#8]
Since the majority of this project will be open source, and we expect (at least some) people to use it, we should include a license with the project.

Personally I like the following:

* MIT
* BSD
* GPLv2
* GPLv3
* MIT/Apache-2.0 (dual license)

MIT and BSD should be self-explanatory (very simple, very permissive). I like GPL because it strongly promotes and encourages further open source development. MIT/Apache-2.0 is mostly because Apache-2.0 makes interop easier and MIT is friendly to GPLv2 projects using this code (this is what the Rust project uses).

**Comment by indiv0** [comment]
My personal vote would be for MIT/Apache-2.0, or failing that, pure MIT.

**Comment by TildeBeta** [comment]
MIT
